### ISSUE TITLE
where is my ics

### ISSUE THREAD

**Issue by bifaciall** [bddvlpr/untis-ics-sync#12]
ive done it with the docker thing and put the conf in the .env if I go to my IP I get: couldnt get /. also I dont know where the ics file is so I cant add it to my calendar

**Comment by bddvlpr** [comment]
First find your class ID in the `/classes` endpoint, then use `/timetables/<classId>` to retrieve the timetables for the given class.

**Comment by bifaciall** [comment]
Ok, thanks. How do I set up SSL it just says to put the cert.pem and key.pem files in a ssl folder but where/how do I get those files

**Comment by bifaciall** [comment]
Also when I do .../classes I get all classes but when I do .../classes/id I get: Cannot get /classes/ID

**Comment by bifaciall** [comment]
And do I have to do SSL or is that optional

**Comment by bddvlpr** [comment]
SSL support is discontinued, use a reverse proxy like [caddy](https://caddyserver.com), [caddy-docker-proxy](https://github.com/lucaslorentz/caddy-docker-proxy) or [nginx](https://nginx.org) to set up a reverse proxy.

**Comment by bifaciall** [comment]
This is what I get when I put it into the field in the calendar app on my ipad: IP:3000/timetables/825. I get the Error that "Validation failed"

**Comment by bifaciall** [comment]
> SSL support is discontinued, use a reverse proxy like [caddy](https://caddyserver.com), [caddy-docker-proxy](https://github.com/lucaslorentz/caddy-docker-proxy) or [nginx](https://nginx.org) to set up a reverse proxy.

Does it not work otherwise with the ical?

**Comment by bifaciall** [comment]
when I have my proxy running, do I just need to add the network in the docker-compose.yml of the ical sync?

**Comment by bifaciall** [comment]
> You can use an insecure connection on iOS, if i recall correctly. ![image](https://user-images.githubusercontent.com/17461028/200295006-4c4655d1-1312-4e5e-851e-4700fdea5ea8.jpeg)
> 
> Open the URL in your browser and check if you get an actual timetable back in ical format.

doesnt work for me

**Comment by bifaciall** [comment]
I dont even get that message

**Comment by bifaciall** [comment]
I just get that the validation failed

**Comment by bifaciall** [comment]
> This is what I get when I put it into the field in the calendar app on my ipad: IP:3000/timetables/825. I get the Error that the "Validation failed"

this is what I entered: IP:3000/timetables/825

**Comment by bddvlpr** [comment]
Open that url in a browser and see if you get an ical output.

**Comment by bifaciall** [comment]
and otherwise it doesnt work

**Comment by bifaciall** [comment]
> Open that url in a browser and see if you get an ical output.

when I do IP:3000/timetables/825 I get this:
![image](https://user-images.githubusercontent.com/83917104/200296260-ac6f6b75-cfbb-49a0-aba2-fbe1ae741e2e.png)

**Comment by bifaciall** [comment]
http://server.droplb.de/timetables/825 when I do that I get the insecure message but I dont get the ical output its useless

**Comment by bifaciall** [comment]
would it work id I changed the port to 80?

**Comment by bddvlpr** [comment]
Sounds like some DNS issues on your end. The screenshot is indicating that it's clearly providing an ical output. Check your DNS records and/or port forwarding.

**Comment by bifaciall** [comment]
I use a local IP and tried with the public

**Comment by bifaciall** [comment]
but calendar says its invalid as soon as I specify the port 3000

**Comment by bifaciall** [comment]
Works now. Was just buggy

**Comment by Julian-1-2-3-4-5** [comment]
I now have the same issue, but i can get my classes id, but when i then go to <myurl>/timetables/<classid>  i just get {"statusCode":404,"message":"Cannot GET /timetables/777","error":"Not Found"}
