### ISSUE TITLE
cannot get timetable, but classes is working

### ISSUE THREAD

**Issue by Julian-1-2-3-4-5** [bddvlpr/untis-ics-sync#21]
when trying to get a timetable from <myurl>/timetables/<classid> i just get {"statusCode":404,"message":"Cannot GET /timetables/777","error":"Not Found"} but getting classes from <myurl>/classes is working

**Comment by bddvlpr** [comment]
Sorry, this is a documentation error, the endpoint has changed to `/lessons/<class>/ics`, so `/lessons/777/ics`.

**Comment by Julian-1-2-3-4-5** [comment]
thank you.
Might be a good idea to update the readme
