### ISSUE TITLE
error querying timetables

### ISSUE THREAD

**Issue by gregstr** [bddvlpr/untis-ics-sync#3]
Not sure if I figured out the API correctly. Querying classes and a single class works fine but when getting timetables via ID connection is terminated and I get below error message.
**To Reproduce**

http://10.0.0.102:3000/classes/ - works fine
http://10.0.0.102:3000/timetables/1492 - connection gets dropped and below error message is logged

Error Message:
2022-09-30T21:26:28.634Z info: Serving GET /timetables/1492 from ::ffff:10.0.0.28
/app/src/utils/time.js:20
            .map((teacher) => teacher.longname)
             ^
TypeError: Cannot read properties of undefined (reading 'map')
    at convertLessonToEvent (/app/src/utils/time.js:20:14)
    at /app/src/server/routes/timetables.route.js:77:62
    at Array.map (<anonymous>)
    at /app/src/server/routes/timetables.route.js:77:14
    at Generator.next (<anonymous>)
    at /app/src/server/routes/timetables.route.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/app/src/server/routes/timetables.route.js:4:12)
    at createCalendar (/app/src/server/routes/timetables.route.js:68:74)
    at /app/src/server/routes/timetables.route.js:38:25
Node.js v18.9.0

System details:
- OS: RancherOS
- Docker version: 19.03.11

Thanks for any advise!

**Comment by bddvlpr** [comment]
Either the typings of webuntis are wrong or an invalid response is being sent. I’ll add checks to see if the teacher field actually exists ASAP.
